# Generated by Django 2.1.5 on 2019-02-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='room_id',
            new_name='room',
        ),
    ]
